# FROM python:3.9-slim

# WORKDIR /mlops_team

# # requirements.txt 먼저 복사
# COPY requirements.txt /mlops_team/requirements.txt

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libgomp1 \
#     libomp-dev \
#     curl \
#     git

# COPY . /mlops_team/


# RUN pip install --no-cache-dir -r /mlops_team/requirements.txt

# EXPOSE 8000

# CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]


# 아래에 새로운 Dockerfile.fastapi 작성
FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y build-essential libgomp1 libomp-dev curl git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# FastAPI 전용 requirements 복사 및 설치
COPY mlops_team/requirements/fastapi.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY mlops_team /app

EXPOSE 8000

# CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD uvicorn src.main:app --host 0.0.0.0 --port 8000 & \
    streamlit run streamlit_app/dashboard.py --server.port 8501