version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    ports:
      - "8181:8181"
    volumes:
      - ./airflow.start.sh:/airflow.start.sh
    command: ["bash", "/airflow.start.sh"]
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow.start.sh:/mlflow.start.sh
      - ./mlflow:/mlflow
    command: ["bash", "/mlflow.start.sh"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
