# GitHub Actions workflow for building and testing the API Docker image

name: API CI - Build and Smoke Test

on:
  push:
    branches: [ main, jungmin ]
  pull_request:
    branches: [ main, jungmin ]

jobs:
  build_and_smoke_test_api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in workspace
        run: |
          echo "디버깅용: 현재 작업 디렉토리 (루트):"
          ls -la
          echo "디버깅용: --- mlops_team 디렉토리 내용: ---"
          ls -la ./mlops_team

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 도커 이미지 빌드
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mlops_team/Dockerfile
          push: false # 일단 한번 로컬에서 빌드 해보고 나중에 true로 바꾸자. 그때 태그도 바꿔야될듯
          # push: true
          # tags: welovecherry/weather-api:240528-v1
          tags: welovecherry/weather-api:ci-test # 태그는 임시용, 나중에 바꾸자

      - name: Run container from built image
        run: |
          docker run -d -p 8000:8000 --name weather-api-test welovecherry/weather-api:ci-test
          echo "Waiting for the API to start..."
          sleep 15

      - name: Perform smoke tests
        run: |
          echo "Running smoke tests..."
          curl -f http://localhost:8000/ 
          echo "API is running..."
          curl -f http://localhost:8000/docs
          # curl -f "http://localhost:8000/predict-future-temp?current_temp=10&current_humidity=50&current_windspeed=1&current_hour=12"

      - name: Stop and remove test container
        if: always()
        run: |
          docker stop weather-api-test
          docker rm weather-api-test

      